### ISSUE TITLE
Google Voice prohibits signing in using this program

### ISSUE THREAD

**Issue by autoteleology** [Fmstrat/google-voice#1]
![image](https://user-images.githubusercontent.com/71520432/93625680-5ee75280-f9b0-11ea-9d55-c24894607e4d.png)

**Comment by blooalien** [comment]
Same exact issue for me.  (Apologies for the "+1".  Just wanted to "bump" this issue, and get subscribed to it at the same time.)  😉

**Comment by MynockSpit** [comment]
~Looks like it's related to this: https://github.com/nativefier/nativefier/issues/902~

Nope, it's this one: https://github.com/nativefier/nativefier/issues/831

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/google-voice/commit/2c035020eea13e8d8a65f35b6cf99dd993358819. Thanks to @MynockSpit for the direction, will merge his PR into another branch once the npx items are split so he's listed as a contributor. Releases will be up shortly.
